name: Build and deploy to web hosting (cPanel)

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    name: Build and Deploy the API server.
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - run: npm ci

      - run: npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/hosting.key
          chmod 600 ~/.ssh/hosting.key
          cat >>~/.ssh/config <<END
          Host hosting
            HostName $SSH_HOST
            Port $SSH_HOST_PORT
            User $SSH_USER
            IdentityFile ~/.ssh/hosting.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ env.HOSTING_SSH_USER }}
          SSH_KEY: ${{ secrets.HOSTING_SSH_KEY }}
          SSH_HOST: ${{ env.HOSTING_SSH_HOST }}
          SSH_HOST_PORT: ${{ env.HOSTING_SSH_HOST_PORT }}

      - name: Stop the node app
        run: ssh hosting "/usr/sbin/cloudlinux-selector stop --json --interpreter nodejs --app-root $HOSTING_APP_ROOT"

      - name: Remove old distribution
        run: ssh hosting "rm -rf $HOSTING_APP_ROOT/dist"

      - name: Copy package IdentityFile
        run: scp package.json "hosting:$HOSTING_APP_ROOT"

      - name: Copy package lock
        run: scp package-lock.json "hosting:$HOSTING_APP_ROOT"

      - name: Copy distribution
        run: scp -r dist/ "hosting:$HOSTING_APP_ROOT"

      - name: Install modules
        run: ssh hosting "/usr/sbin/cloudlinux-selector install-modules --json --interpreter nodejs --app-root $HOSTING_APP_ROOT"

      - name: Start the node app
        run: ssh hosting "/usr/sbin/cloudlinux-selector start --json --interpreter nodejs --app-root $HOSTING_APP_ROOT"
